import string

# SYNTAX SETTINGS
WHITE_CHARS         = list(string.whitespace)

IDENTIFIERS         = list(string.ascii_letters + string.digits)

OPENING_BRACKET     = '('
CLOSING_BRACKET     = ')'
BRACKETS            = [OPENING_BRACKET, CLOSING_BRACKET]

AND_OPERATOR        = '&'
OR_OPERATOR         = '|'
XOR_OPERATOR        = '^'
NOT_OPERATOR        = '~'
IMPL_OPERATOR       = '>'
XNOR_OPERATOR       = '='
SINGLE_OPERATORS    = [NOT_OPERATOR]
DOUBLE_OPERATORS    = [AND_OPERATOR, OR_OPERATOR, XOR_OPERATOR, IMPL_OPERATOR, XOR_OPERATOR]
OPERATORS           = SINGLE_OPERATORS + DOUBLE_OPERATORS

TRUE_CONSTANT       = '1'
FALSE_CONSTANT      = '0'
CONSTANTS           = [TRUE_CONSTANT, FALSE_CONSTANT]

VALID_CHARS         = WHITE_CHARS + IDENTIFIERS + BRACKETS + OPERATORS + CONSTANTS
